
package comprador.gui;

import comprador.Compra;
import comprador.Comprador;
import comprador.Puja;
import java.util.ArrayList;


public class CompradorGUI extends javax.swing.JFrame {

    private Comprador comprador;
    private ArrayList<String> notificaciones;
    private Puja pujaActual;
    
    public CompradorGUI(Comprador comprador) {
        initComponents();
        this.setVisible(true);
        this.comprador = comprador;
        this.txtError.setVisible(false);
        this.txtErrorElim.setVisible(false);
        this.notificaciones = new ArrayList<>();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompras = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaCompras = new javax.swing.JTable();
        panelPujar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        buttonPujar = new javax.swing.JButton();
        txtError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelPujas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPujas = new javax.swing.JTable();
        buttonSalirPuja = new javax.swing.JButton();
        txtErrorElim = new javax.swing.JLabel();
        panelNotificaciones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaNotificaciones = new javax.swing.JTable();
        buttonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(645, 694));
        setResizable(false);

        panelCompras.setBackground(new java.awt.Color(164, 164, 164));
        panelCompras.setForeground(new java.awt.Color(1, 1, 1));
        panelCompras.setName("panelCompras"); // NOI18N

        jLabel8.setBackground(new java.awt.Color(164, 164, 164));
        jLabel8.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Compras");
        jLabel8.setName("jLabel8"); // NOI18N

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        tablaCompras.setModel(new ModeloTablaCompras());
        tablaCompras.setName("tablaCompras"); // NOI18N
        jScrollPane3.setViewportView(tablaCompras);

        org.jdesktop.layout.GroupLayout panelComprasLayout = new org.jdesktop.layout.GroupLayout(panelCompras);
        panelCompras.setLayout(panelComprasLayout);
        panelComprasLayout.setHorizontalGroup(
            panelComprasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelComprasLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelComprasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelComprasLayout.setVerticalGroup(
            panelComprasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelComprasLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .add(16, 16, 16))
        );

        panelPujar.setBackground(new java.awt.Color(164, 164, 164));
        panelPujar.setForeground(new java.awt.Color(1, 1, 1));
        panelPujar.setName("panelPujar"); // NOI18N

        jLabel3.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Precio");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("URW Gothic L", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Nombre");
        jLabel4.setName("jLabel4"); // NOI18N

        txtNombre.setBackground(new java.awt.Color(222, 222, 222));
        txtNombre.setName("txtNombre"); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        txtPrecio.setBackground(new java.awt.Color(222, 222, 222));
        txtPrecio.setName("txtPrecio"); // NOI18N

        buttonPujar.setText("PUJAR");
        buttonPujar.setName("buttonPujar"); // NOI18N
        buttonPujar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPujarActionPerformed(evt);
            }
        });

        txtError.setBackground(new java.awt.Color(254, 254, 254));
        txtError.setFont(new java.awt.Font("URW Gothic L", 3, 14)); // NOI18N
        txtError.setForeground(new java.awt.Color(197, 9, 9));
        txtError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtError.setText("ERROR");
        txtError.setName("txtError"); // NOI18N

        jLabel2.setBackground(new java.awt.Color(164, 164, 164));
        jLabel2.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nueva puja");
        jLabel2.setName("jLabel2"); // NOI18N

        org.jdesktop.layout.GroupLayout panelPujarLayout = new org.jdesktop.layout.GroupLayout(panelPujar);
        panelPujar.setLayout(panelPujarLayout);
        panelPujarLayout.setHorizontalGroup(
            panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPujarLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtError, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelPujarLayout.createSequentialGroup()
                        .add(panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, buttonPujar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(panelPujarLayout.createSequentialGroup()
                                .add(panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 78, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel3))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(txtPrecio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .add(txtNombre))))
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPujarLayout.setVerticalGroup(
            panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPujarLayout.createSequentialGroup()
                .add(27, 27, 27)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .add(28, 28, 28)
                .add(panelPujarLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(txtPrecio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 43, Short.MAX_VALUE)
                .add(txtError)
                .add(35, 35, 35)
                .add(buttonPujar)
                .addContainerGap())
        );

        panelPujas.setBackground(new java.awt.Color(164, 164, 164));
        panelPujas.setForeground(new java.awt.Color(1, 1, 1));
        panelPujas.setName("panelPujas"); // NOI18N

        jLabel1.setBackground(new java.awt.Color(254, 254, 254));
        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pujas Activas");
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        tablaPujas.setModel(new ModeloTablaPujasActivasComprador());
        tablaPujas.setName("tablaPujas"); // NOI18N
        tablaPujas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPujasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPujas);

        buttonSalirPuja.setText("Eliminar puja");
        buttonSalirPuja.setName("buttonSalirPuja"); // NOI18N
        buttonSalirPuja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirPujaActionPerformed(evt);
            }
        });

        txtErrorElim.setBackground(new java.awt.Color(254, 254, 254));
        txtErrorElim.setFont(new java.awt.Font("URW Gothic L", 3, 14)); // NOI18N
        txtErrorElim.setForeground(new java.awt.Color(197, 9, 9));
        txtErrorElim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtErrorElim.setText("ERROR");
        txtErrorElim.setName("txtErrorElim"); // NOI18N

        org.jdesktop.layout.GroupLayout panelPujasLayout = new org.jdesktop.layout.GroupLayout(panelPujas);
        panelPujas.setLayout(panelPujasLayout);
        panelPujasLayout.setHorizontalGroup(
            panelPujasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPujasLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelPujasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelPujasLayout.createSequentialGroup()
                        .add(panelPujasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(panelPujasLayout.createSequentialGroup()
                                .add(8, 8, 8)
                                .add(buttonSalirPuja, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtErrorElim, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPujasLayout.setVerticalGroup(
            panelPujasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelPujasLayout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jLabel1)
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 22, Short.MAX_VALUE)
                .add(txtErrorElim)
                .add(18, 18, 18)
                .add(buttonSalirPuja)
                .addContainerGap())
        );

        panelNotificaciones.setBackground(new java.awt.Color(164, 164, 164));
        panelNotificaciones.setForeground(new java.awt.Color(1, 1, 1));
        panelNotificaciones.setName("panelNotificaciones"); // NOI18N

        jLabel5.setBackground(new java.awt.Color(254, 247, 247));
        jLabel5.setFont(new java.awt.Font("URW Gothic L", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Notificaciones");
        jLabel5.setName("jLabel5"); // NOI18N

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        tablaNotificaciones.setModel(new ModeloTablaNotificacionesComprador());
        tablaNotificaciones.setName("tablaNotificaciones"); // NOI18N
        jScrollPane2.setViewportView(tablaNotificaciones);

        buttonSalir.setText("Salir");
        buttonSalir.setName("buttonSalir"); // NOI18N
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout panelNotificacionesLayout = new org.jdesktop.layout.GroupLayout(panelNotificaciones);
        panelNotificaciones.setLayout(panelNotificacionesLayout);
        panelNotificacionesLayout.setHorizontalGroup(
            panelNotificacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelNotificacionesLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelNotificacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, panelNotificacionesLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(buttonSalir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelNotificacionesLayout.setVerticalGroup(
            panelNotificacionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelNotificacionesLayout.createSequentialGroup()
                .add(26, 26, 26)
                .add(jLabel5)
                .add(18, 18, 18)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .add(17, 17, 17)
                .add(buttonSalir)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(panelPujar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(panelCompras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(panelPujas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(panelNotificaciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(panelCompras, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelPujar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(panelPujas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(panelNotificaciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void buttonPujarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPujarActionPerformed
        this.txtError.setVisible(false);
        if(!txtNombre.getText().equals("") && !txtPrecio.getText().equals("")){
            try{
                Boolean flag = this.comprador.anhadirPuja(new Puja(txtNombre.getText(),Double.parseDouble(txtPrecio.getText())));
                if(!flag) this.txtError.setVisible(true);
            }catch(Exception e){
                System.out.println("Exception: "+ e);
                this.txtError.setVisible(true);
            }
        }else{
            this.txtError.setVisible(true);
        }
    }//GEN-LAST:event_buttonPujarActionPerformed

    private void buttonSalirPujaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirPujaActionPerformed
        if(this.pujaActual != null){
            if(!this.pujaActual.isGanador()){
                this.comprador.eliminarPuja(this.pujaActual);
                actualizarTablaPujas();
            }else{
                this.txtErrorElim.setVisible(false);
            }
        }
    }//GEN-LAST:event_buttonSalirPujaActionPerformed

    private void tablaPujasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPujasMouseClicked
        this.buttonSalirPuja.setEnabled(false);
        this.txtErrorElim.setVisible(false);
        ModeloTablaPujasActivasComprador m;
        m = (ModeloTablaPujasActivasComprador) this.tablaPujas.getModel();
        Puja puja = m.obtenerPuja(this.tablaPujas.getSelectedRow());
        if (puja != null) {
            this.pujaActual = puja;
            this.buttonSalirPuja.setEnabled(true);
        }else{
            pujaActual = null;
        }
    }//GEN-LAST:event_tablaPujasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPujar;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JButton buttonSalirPuja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelCompras;
    private javax.swing.JPanel panelNotificaciones;
    private javax.swing.JPanel panelPujar;
    private javax.swing.JPanel panelPujas;
    private javax.swing.JTable tablaCompras;
    private javax.swing.JTable tablaNotificaciones;
    private javax.swing.JTable tablaPujas;
    private javax.swing.JLabel txtError;
    private javax.swing.JLabel txtErrorElim;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    public void actualizarTablaPujas(){
        ((ModeloTablaPujasActivasComprador) tablaPujas.getModel()).setFilas(this.comprador.getPujasActivas());
    }
    
    public void actualizarTablaNotificaciones(){
        ((ModeloTablaNotificacionesComprador) tablaNotificaciones.getModel()).setFilas(this.notificaciones);
    }
    
    public void nuevaNotificaion(String notificacion){
        ((ModeloTablaNotificacionesComprador) tablaNotificaciones.getModel()).nuevaNotificaion(notificacion);
    }
    
    public void nuevaCompra(String libro, Double precio){
        ((ModeloTablaCompras) tablaCompras.getModel()).nuevaCompra(new Compra(libro,precio));
    }
    
    /*
    public void nuevaNotificaion(String notificacion){
       ArrayList<String> aux = new ArrayList<>();
       aux.add(notificacion);
       for(String n: this.notificaciones){
           aux.add(n);
       }
       this.notificaciones = aux;
       // ((ModeloTablaNotificacionesComprador) tablaNotificaciones).nuevaNotificaion(notificacion);
    }
*/
}
